ids: [b070ee4b-027d-44b1-a259-cebe19f13090, 0af4f974-e124-4f42-94aa-d18d9601563f,
  452780af-9a79-4ed7-9f66-6bd3fa2ffd39, bfc7348c-54bd-4c2e-8d21-8c8fbc37eb29, 1bb5b8d3-cb11-4c54-b8a6-4127865931bd]
sessions:
  jack:
  - &id001 !set
    expId: 3b6edbea-f697-48e9-aa5c-8da5bce213fc
    feedback: {helper: true, audio: false, slots: true, coins: true, realtime: true}
    normId: 441b8a8f-a0f1-4f95-b7b2-a8f5acf130f3
    numTrials: 2
    sensitivityAperture: 1.0
    sensitivityRotation: 0.5
    sensitivityTrajectory: 0.5
  - &id002 !set
    expId: 3b6edbea-f697-48e9-aa5c-8da5bce213fc
    feedback: {helper: false, audio: false, slots: true, coins: true, realtime: true}
    normId: 441b8a8f-a0f1-4f95-b7b2-a8f5acf130f3
    numTrials: 11
    sensitivityAperture: 2.2
    sensitivityRotation: 2.1
    sensitivityTrajectory: 2.0
  - *id001
  foobar:
  - *id001
  jack2:
  - *id002
  - *id002
